// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Vitest from "vitest";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Vitest$1 from "@epure/vitest";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

Vitest$1.Given("I have a table", (param, data) => {
  let step = param.step;
  let match = Tilia.signal([]);
  let setRecords = match[1];
  let records = match[0];
  let match$1 = Tilia.signal({
    name: "",
    age: ""
  });
  let setRecord = match$1[1];
  let record = match$1[0];
  step("I convert the table to records", () => setRecords(Vitest$1.toRecords(data)));
  step("I select record {number}", index => setRecord(Stdlib_Option.getOrThrow(records.value[index], undefined)));
  step("selected name should be {string}", value => Vitest.expect(record.value.name).toBe(value));
  step("selected age should be {number}", value => Vitest.expect(Stdlib_Int.fromString(record.value.age, undefined)).toBe(value));
});

/*  Not a pure module */
