// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Vitest$1 from "@epure/vitest";
import * as ResCalculator from "../../feature/ResCalculator.mjs";

Vitest$1.Given("a calculator loaded from {string}", async (param, name) => {
  let calculator = ResCalculator.make(name);
  await Promise.resolve();
  calculator.add(3, 4);
  return param.step("the result is {number}", n => Vitest.expect(calculator.result).toBe(n));
});

/*  Not a pure module */
