// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Vitest$1 from "@epure/vitest";
import * as ResCalculator from "../../feature/ResCalculator.mjs";

Vitest$1.Given("a calculator", (param, param$1) => {
  let step = param.step;
  let calculator = ResCalculator.make("basic");
  let numbers = {
    contents: []
  };
  step("I have {number} and {number} and {number}", (a, b, c) => {
    numbers.contents = [
      a,
      b,
      c
    ];
  });
  step("I add them all", () => {
    calculator.add(0, 0);
    numbers.contents.forEach(number => calculator.add(calculator.result, number));
  });
  step("the result is {number}", n => Vitest.expect(calculator.result).toBe(n));
});

/*  Not a pure module */
