// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

function make(name) {
  let match = Tilia.signal(0);
  let setResult = match[1];
  let result = match[0];
  return Tilia.tilia({
    add: (a, b) => setResult(a + b),
    subtract: (a, b) => setResult(a - b),
    multiply: (a, b) => setResult(a * b),
    divide: (a, b) => setResult(a / b),
    result: Tilia.computed(() => result.value),
    title: name
  });
}

export {
  make,
}
/* Tilia Not a pure module */
