// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let MyException = /* @__PURE__ */Primitive_exceptions.create("VitestBdd_test.MyException");

Vitest.describe("VitestBdd", () => {
  Vitest.it("should match snapshot", () => Vitest.expect({
    name: "John",
    age: 31
  }).toMatchSnapshot(undefined));
  Vitest.it("should match object", () => Vitest.expect({
    name: "John",
    age: 31
  }).toMatchObject({
    name: "John",
    age: 31
  }));
  Vitest.it("should support .not modifier", () => Vitest.expect(1).not.toBe(2));
  Vitest.it("should support .soft modifier", () => Vitest.expect.soft(1).toBe(1));
  Vitest.it("should support .poll modifier", async () => Vitest.expect.poll(() => 42, {
    interval: 10,
    timeout: 50
  }).toBe(42));
  Vitest.it("should support toBe", () => Vitest.expect(1).toBe(1));
  Vitest.it("should compile with multiple assertions", () => {
    Vitest.expect.assertions(2);
    Vitest.expect(1).toBe(1);
    Vitest.expect(2).toBe(2);
  });
  Vitest.it("should support toEqual", () => Vitest.expect([
    1,
    2,
    3
  ]).toEqual([
    1,
    2,
    3
  ]));
  Vitest.it("should support toStrictEqual", () => Vitest.expect({
    a: 1,
    b: 2
  }).toStrictEqual({
    a: 1,
    b: 2
  }));
  Vitest.it("should support toBeTruthy", () => Vitest.expect(true).toBeTruthy());
  Vitest.it("should support toBeFalsy", () => Vitest.expect(false).toBeFalsy());
  Vitest.it("should support toBeDefined", () => Vitest.expect(1).toBeDefined());
  Vitest.it("should support toBeUndefined", () => Vitest.expect(undefined).toBeUndefined());
  Vitest.it("should support toBeNull", () => Vitest.expect(null).toBeNull());
  Vitest.it("should support toBeNaN", () => Vitest.expect(NaN).toBeNaN());
  Vitest.it("should support toBeTypeOf", () => Vitest.expect("hello").toBeTypeOf("string"));
  Vitest.it("should support toBeCloseTo", () => Vitest.expect(3.14159).toBeCloseTo(3.14, 2));
  Vitest.it("should support toBeGreaterThan", () => Vitest.expect(5.0).toBeGreaterThan(4.0));
  Vitest.it("should support toBeGreaterThanOrEqual", () => Vitest.expect(5.0).toBeGreaterThanOrEqual(5.0));
  Vitest.it("should support toBeLessThan", () => Vitest.expect(3.0).toBeLessThan(4.0));
  Vitest.it("should support toBeLessThanOrEqual", () => Vitest.expect(4.0).toBeLessThanOrEqual(4.0));
  Vitest.it("should support toMatch", () => Vitest.expect("hello world").toMatch(/world/));
  Vitest.it("should support toMatchInlineSnapshot", () => Vitest.expect({
    foo: "bar"
  }).toMatchInlineSnapshot(undefined, `{
  "foo": "bar",
}`));
  Vitest.it("should support toMatchSnapshot", () => Vitest.expect({
    name: "John",
    age: 30
  }).toMatchSnapshot(undefined));
  Vitest.it("should support toContain", () => Vitest.expect([
    1,
    2,
    3
  ]).toContain(2));
  Vitest.it("should support toContainEqual", () => Vitest.expect([
    {
      a: 1
    },
    {
      a: 2
    }
  ]).toContainEqual({
    a: 2
  }));
  Vitest.it("should support toHaveLength", () => Vitest.expect([
    1,
    2,
    3
  ]).toHaveLength(3));
  Vitest.it("should support toHaveProperty", () => Vitest.expect({
    foo: 42,
    bar: 7
  }).toHaveProperty("foo", 42));
  Vitest.it("should support toBeOneOf", () => Vitest.expect(2).toBeOneOf([
    1,
    2,
    3
  ]));
  Vitest.it("should support toThrow", () => {
    let f = () => {
      throw {
        RE_EXN_ID: "Failure",
        _1: "fail",
        Error: new Error()
      };
    };
    Vitest.expect(f).toThrow(undefined);
  });
  Vitest.it("should support toThrowError", () => {
    let f = () => {
      throw {
        RE_EXN_ID: "Failure",
        _1: "fail",
        Error: new Error()
      };
    };
    Vitest.expect(f).toThrowError(undefined, "fail");
  });
  Vitest.it("should support resolves", async () => {
    let promise = Promise.resolve(42);
    return Vitest.expect(promise).resolves.toBe(42);
  });
  Vitest.it("should force await on resolves", async () => {
    let promise = Promise.resolve(42);
    await Vitest.expect(promise).resolves.toBe(42);
    return Vitest.expect(1).toBe(1);
  });
  Vitest.it("should support rejects", async () => {
    let promise = Promise.reject({
      RE_EXN_ID: MyException,
      _1: "fail"
    });
    return await Vitest.expect(promise).rejects.toMatchObject({
      RE_EXN_ID: MyException,
      _1: "fail"
    });
  });
  Vitest.it("should support toSatisfy", () => Vitest.expect(10).toSatisfy(x => x > 5));
  Vitest.it("should support toMatchObject", () => Vitest.expect({
    a: 1,
    b: 2
  }).toMatchObject({
    a: 1
  }));
  Vitest.it("should support toMatchFileSnapshot", async () => await Vitest.expect("blah blah").toMatchFileSnapshot("blah-blah.txt", undefined));
  Vitest.it("should support toThrowErrorMatchingSnapshot", () => {
    let f = () => {
      throw {
        RE_EXN_ID: "Failure",
        _1: "fail",
        Error: new Error()
      };
    };
    Vitest.expect(f).toThrowErrorMatchingSnapshot(undefined);
  });
  Vitest.it("should support toThrowErrorMatchingInlineSnapshot", () => {
    let f = () => {
      throw {
        RE_EXN_ID: "Failure",
        _1: "fail",
        Error: new Error()
      };
    };
    Vitest.expect(f).toThrowErrorMatchingInlineSnapshot(undefined, `{ 
      "Failure": "fail"
    }`);
  });
  Vitest.it("should support .not modifier", () => {
    Vitest.expect.assertions(1);
    Vitest.expect(1).toBe(1);
  });
  Vitest.it("compare float in object properties", () => Vitest.expect({
    title: "0.1 + 0.2",
    sum: 0.1 + 0.20002
  }).toEqual({
    title: "0.1 + 0.2",
    sum: Vitest.expect.closeTo(0.3, 2)
  }));
  Vitest.it("should support expected.anything in toEqual", () => Vitest.expect({
    a: 1,
    b: 2
  }).toEqual({
    a: Vitest.expect.anything(),
    b: Vitest.expect.anything()
  }));
  Vitest.it("should support expected.any in toEqual", () => Vitest.expect({
    name: "John",
    age: 30
  }).toEqual({
    name: Vitest.expect.any(String),
    age: Vitest.expect.any(Number)
  }));
  Vitest.it("should support expected.arrayContaining in toEqual", () => Vitest.expect({
    list: [
      1,
      2,
      3
    ]
  }).toEqual({
    list: Vitest.expect.arrayContaining([2])
  }));
  Vitest.it("should support expected.objectContaining in toEqual", () => Vitest.expect({
    a: 1,
    b: 2
  }).toEqual(Vitest.expect.objectContaining({
    a: 1
  })));
  Vitest.it("should support expected.stringContaining in toEqual", () => Vitest.expect({
    name: "hello world",
    age: 30
  }).toEqual({
    name: Vitest.expect.stringContaining("world"),
    age: Vitest.expect.any(Number)
  }));
  Vitest.it("should support expected.stringMatching in toEqual", () => Vitest.expect({
    name: "abc123",
    age: 30
  }).toEqual({
    name: Vitest.expect.stringMatching(/\d+/),
    age: Vitest.expect.any(Number)
  }));
  Vitest.it("should support addSnapshotSerializer", () => {
    let called = {
      contents: false
    };
    let serializer_test = _value => {
      called.contents = true;
      return true;
    };
    let serializer_print = _value => "serialized";
    let serializer = {
      test: serializer_test,
      print: serializer_print
    };
    Vitest.expect.addSnapshotSerializer(serializer);
    Vitest.expect(called.contents).toBe(false);
  });
  Vitest.it("should support extend for custom matchers", () => {
    let matcher = {
      toBeFoo: value => {
        if (value === "foo") {
          return {
            pass: true,
            message: () => "ok"
          };
        } else {
          return {
            pass: false,
            message: () => "not foo"
          };
        }
      }
    };
    Vitest.expect.extend(matcher);
    Vitest.expect(true).toBeTruthy();
  });
  Vitest.it("should support addEqualityTesters", () => {
    let tester = Primitive_object.equal;
    Vitest.expect.addEqualityTesters([tester]);
    Vitest.expect(true).toBeTruthy();
  });
});

export {
  MyException,
}
/*  Not a pure module */
